name: movie_avilatek_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  dotenv: ^4.2.0
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.5
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^12.0.1
  shadow_overlay: ^1.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: BalooBold
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
    - family: Baloo2Regular
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf

